"""empty message

Revision ID: 0770c3e46e72
Revises: 8e6374ad5042
Create Date: 2020-12-08 18:40:23.752213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0770c3e46e72'
down_revision = '8e6374ad5042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart__product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.String(length=120), nullable=False),
    sa.Column('img', sa.String(length=120), nullable=False),
    sa.Column('continent', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('continent'),
    sa.UniqueConstraint('country'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('price')
    )
    op.drop_index('continent', table_name='cart')
    op.drop_index('country', table_name='cart')
    op.drop_index('img', table_name='cart')
    op.drop_index('name', table_name='cart')
    op.drop_index('price', table_name='cart')
    op.drop_table('cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('img', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('continent', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('price', 'cart', ['price'], unique=True)
    op.create_index('name', 'cart', ['name'], unique=True)
    op.create_index('img', 'cart', ['img'], unique=True)
    op.create_index('country', 'cart', ['country'], unique=True)
    op.create_index('continent', 'cart', ['continent'], unique=True)
    op.drop_table('cart__product')
    # ### end Alembic commands ###
