"""empty message

Revision ID: 36085997fec4
Revises: 3823c80ff8ea
Create Date: 2021-01-06 19:08:16.179717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36085997fec4'
down_revision = '3823c80ff8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('description', mysql.VARCHAR(length=500), nullable=False))
    # ### end Alembic commands ###
